#!/bin/bash

#SBATCH --job-name=iow_rcsm 
#SBATCH --nodes=_NODES_
#SBATCH --ntasks=_CORES_
#SBATCH --tasks-per-node _CORESPERNODE_
#SBATCH -t 00:20:00
#SBATCH --account=iow 
#SBATCH -p compute
#SBATCH --distribution=block,Pack

export SLURM_CPU_BIND=none

module load intel/19.1.0 
module load openmpi/intel.19/3.1.6
module load miniconda3

python3 run.py

