#!/bin/bash

#SBATCH --job-name=iow_rcsm 
#SBATCH --nodes=_NODES_
#SBATCH --ntasks=_CORES_
#SBATCH --tasks-per-node _CORESPERNODE_
#SBATCH -t 00:20:00
#SBATCH --account=mvk00050 
#SBATCH -p standard96:test
#SBATCH --distribution=block,Pack

export SLURM_CPU_BIND=none

module load intel/18.0.6
module load impi/2018.5
module load anaconda3

python3 run.py

