#!/bin/bash
###################################################################
# This script links all forcing data to the corresponding folders #
###################################################################
# remove dirs if they exist
rm -r OBC
rm -r ATMDEP
rm -r RIVER

# Sea level at open boundary (annual files)
mkdir OBC
mkdir OBC/from
ln -s /scratch/usr/mviowmod/DATABASE/METEO/coastDat-2_COSMO-CLM/OBC_TROP_8nm/* OBC/from/

# baroclinic OBC information (periodic)
ln -s /scratch/usr/mviowmod/DATABASE/OBC_CLIN/SKAG_8nm/obc_clin_west.dta.nc OBC/

# atmospheric deposition (annual files)
mkdir ATMDEP
mkdir ATMDEP/from
ln -s /scratch/usr/mviowmod/DATABASE/ATM_LOADS/reconstruction-1850-2010/8nm/* ATMDEP/from/

# river and diffusive loads (annual files)
mkdir RIVER
mkdir RIVER/from
ln -s /scratch/usr/mviowmod/DATABASE/RIVER/level-2/DIFF_LOADS_8nm/* RIVER/from/
for DIR in RIVER/from/*; do
  YEAR=$(basename $DIR)
  ln -s /scratch/usr/mviowmod/DATABASE/RIVER/level-2/reconstruction-1850-2000/8nm/$YEAR/* RIVER/from/$YEAR/
done
